"""Tests for the runtime-artifact inventory + reaper (orphan cleanup).

Hermetic: process logic is driven by patching the ``server_proc`` primitives
(``find_listening_pid`` / ``_read_cmdline`` / ``reclaim_stale_port``); unit logic
uses real files under a tmp ``XDG_CONFIG_HOME`` with ``subprocess.run`` recorded;
the shim is a real tmp file. ``_is_macos`` is forced False so every test exercises
the Linux/systemd path regardless of host.
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any

import pytest

from agentalloy.install import runtime_artifacts as ra

_MATCH: dict[int, tuple[str, ...]] = dict(ra.RUNTIME_PORTS)


def _ours_cmdline(port: int) -> str:
    """A cmdline that satisfies the foreign-safe matcher for *port*."""
    return " ".join(_MATCH[port]) + f" --port {port} -m /models/x.gguf"


def _write_shim(path: Path, *, sentinel: bool, target_exists: bool, runtime_dir: Path) -> None:
    runtime_dir.mkdir(parents=True, exist_ok=True)
    if target_exists:
        (runtime_dir / "llama-server").write_text("binary")
    header = (
        "#!/bin/sh\n# Auto-generated by `agentalloy pull-models`.\n"
        if sentinel
        else "#!/bin/sh\n# my own llama-server launcher\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        header + f'LLAMA_LIB_DIR="{runtime_dir}"\nexec "$LLAMA_LIB_DIR/llama-server" "$@"\n'
    )


@pytest.fixture
def force_linux(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(ra, "_is_macos", lambda: False)


@pytest.fixture
def systemd_dir(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    unit_dir = tmp_path / "config" / "systemd" / "user"
    unit_dir.mkdir(parents=True)
    monkeypatch.setenv("XDG_CONFIG_HOME", str(tmp_path / "config"))
    return unit_dir


@pytest.fixture
def rec_subprocess(monkeypatch: pytest.MonkeyPatch) -> list[list[str]]:
    calls: list[list[str]] = []

    def fake_run(cmd: list[str], *a: Any, **k: Any) -> subprocess.CompletedProcess[str]:
        calls.append(list(cmd))
        return subprocess.CompletedProcess(cmd, 0, stdout="", stderr="")

    monkeypatch.setattr(ra.subprocess, "run", fake_run)
    return calls


@pytest.fixture(autouse=True)
def _native_mode(monkeypatch: pytest.MonkeyPatch) -> None:
    """Default to native mode so port logic is host-independent.

    Without this, ``_agentalloy_container_running`` would shell out to a real
    ``podman``/``docker`` on the test host (and pass/fail depending on whether
    an ``agentalloy`` container happens to be up). Container-aware tests opt
    back in by patching it to return True.
    """
    monkeypatch.setattr(ra, "_agentalloy_container_running", lambda: False)


# --- process reaping -------------------------------------------------------


def test_reap_processes_reaps_ours_spares_foreign(
    monkeypatch: pytest.MonkeyPatch, force_linux: None
) -> None:
    monkeypatch.setattr(ra.server_proc, "find_listening_pid", lambda port, **k: port)

    def fake_cmdline(pid: int) -> str:
        return "nginx: master process" if pid == ra.RERANK_PORT else _ours_cmdline(pid)

    monkeypatch.setattr(ra.server_proc, "_read_cmdline", fake_cmdline)

    reclaimed: list[int] = []

    def fake_reclaim(port: int, match: list[str]) -> int | None:
        reclaimed.append(port)
        return port

    monkeypatch.setattr(ra.server_proc, "reclaim_stale_port", fake_reclaim)

    actions = ra.reap("processes")
    stops = [a for a in actions if a.op == "stop_process" and a.executed]
    warns = [a for a in actions if a.op == "warn_foreign"]

    assert len(stops) == 2
    assert len(warns) == 1
    # The foreign holder on the rerank port is NEVER reclaimed.
    assert ra.RERANK_PORT not in reclaimed
    assert set(reclaimed) == {ra.SERVICE_PORT, ra.EMBED_PORT}


def test_reap_processes_noop_when_ports_free(
    monkeypatch: pytest.MonkeyPatch, force_linux: None
) -> None:
    monkeypatch.setattr(ra.server_proc, "find_listening_pid", lambda port, **k: None)
    assert ra.reap("processes") == []


# --- dry-run: zero side effects --------------------------------------------


def test_reap_all_dry_run_has_no_side_effects(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    force_linux: None,
    systemd_dir: Path,
    rec_subprocess: list[list[str]],
) -> None:
    (systemd_dir / "agentalloy.service").write_text("[Service]\n")
    shim = tmp_path / "bin" / "llama-server"
    _write_shim(shim, sentinel=True, target_exists=False, runtime_dir=tmp_path / "rt")
    monkeypatch.setattr(ra, "shim_path", lambda: shim)

    monkeypatch.setattr(ra.server_proc, "find_listening_pid", lambda port, **k: port)
    monkeypatch.setattr(ra.server_proc, "_read_cmdline", _ours_cmdline)
    reclaim_calls: list[int] = []
    monkeypatch.setattr(ra.server_proc, "reclaim_stale_port", lambda p, m: reclaim_calls.append(p))

    actions = ra.reap("all", dry_run=True)

    # The plan is populated...
    assert any(a.op == "remove_unit" for a in actions)
    assert any(a.op == "remove_shim" for a in actions)
    assert any(a.op == "stop_process" for a in actions)
    # ...but nothing was executed.
    assert all(not a.executed for a in actions)
    assert reclaim_calls == []
    assert rec_subprocess == []
    assert (systemd_dir / "agentalloy.service").exists()
    assert shim.exists()


# --- service units ---------------------------------------------------------


def test_reap_services_removes_all_units_and_env(
    force_linux: None, systemd_dir: Path, rec_subprocess: list[list[str]]
) -> None:
    for unit in ra.SYSTEMD_UNITS:
        (systemd_dir / unit).write_text("[Service]\n")
    (systemd_dir / "agentalloy.env").write_text("X=1\n")

    ra.reap("services")

    for unit in ra.SYSTEMD_UNITS:
        assert not (systemd_dir / unit).exists(), unit
    assert not (systemd_dir / "agentalloy.env").exists()
    disables = [c for c in rec_subprocess if c[:4] == ["systemctl", "--user", "disable", "--now"]]
    assert len(disables) == len(ra.SYSTEMD_UNITS)
    assert any(c[:3] == ["systemctl", "--user", "daemon-reload"] for c in rec_subprocess)


def test_reap_services_stale_only_keeps_live_units(
    monkeypatch: pytest.MonkeyPatch,
    force_linux: None,
    systemd_dir: Path,
    rec_subprocess: list[list[str]],
) -> None:
    for unit in ra.SYSTEMD_UNITS:
        (systemd_dir / unit).write_text("[Service]\n")
    # Only the embed port is reachable → its unit is healthy and must be kept.
    monkeypatch.setattr(ra.server_proc, "port_reachable", lambda port, **k: port == ra.EMBED_PORT)

    ra.reap("services", stale_only=True)

    assert (systemd_dir / "agentalloy-embed.service").exists()
    assert not (systemd_dir / "agentalloy.service").exists()
    assert not (systemd_dir / "agentalloy-rerank.service").exists()


# --- shim ------------------------------------------------------------------


def test_reap_shim_requires_sentinel(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, force_linux: None
) -> None:
    shim = tmp_path / "bin" / "llama-server"
    _write_shim(shim, sentinel=False, target_exists=True, runtime_dir=tmp_path / "rt")
    monkeypatch.setattr(ra, "shim_path", lambda: shim)

    assert ra.reap("shim") == []  # a user's own llama-server — never ours to remove
    assert shim.exists()


def test_reap_shim_removes_ours(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, force_linux: None
) -> None:
    shim = tmp_path / "bin" / "llama-server"
    _write_shim(shim, sentinel=True, target_exists=True, runtime_dir=tmp_path / "rt")
    monkeypatch.setattr(ra, "shim_path", lambda: shim)

    actions = ra.reap("shim")
    assert any(a.op == "remove_shim" and a.executed for a in actions)
    assert not shim.exists()


def test_reap_shim_stale_only_keeps_working_shim(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, force_linux: None
) -> None:
    shim = tmp_path / "bin" / "llama-server"
    _write_shim(shim, sentinel=True, target_exists=True, runtime_dir=tmp_path / "rt")
    monkeypatch.setattr(ra, "shim_path", lambda: shim)

    assert ra.reap("shim", stale_only=True) == []  # target present → keep
    assert shim.exists()


def test_reap_shim_stale_only_removes_dangling(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, force_linux: None
) -> None:
    shim = tmp_path / "bin" / "llama-server"
    _write_shim(shim, sentinel=True, target_exists=False, runtime_dir=tmp_path / "rt")
    monkeypatch.setattr(ra, "shim_path", lambda: shim)

    actions = ra.reap("shim", stale_only=True)
    assert any(a.op == "remove_shim" for a in actions)
    assert not shim.exists()


# --- detection -------------------------------------------------------------


def test_detect_orphans_classifies(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, force_linux: None
) -> None:
    monkeypatch.setattr(ra.server_proc, "find_listening_pid", lambda port, **k: port)

    def fake_cmdline(pid: int) -> str:
        return "nginx" if pid == ra.SERVICE_PORT else _ours_cmdline(pid)

    monkeypatch.setattr(ra.server_proc, "_read_cmdline", fake_cmdline)
    # embed unit active (healthy); everything else inactive.
    monkeypatch.setattr(ra, "_unit_active", lambda port: port == ra.EMBED_PORT)

    shim = tmp_path / "bin" / "llama-server"
    _write_shim(shim, sentinel=True, target_exists=False, runtime_dir=tmp_path / "rt")
    monkeypatch.setattr(ra, "shim_path", lambda: shim)

    orphans = ra.detect_orphans()
    kinds = {o.kind for o in orphans}

    assert "conflict" in kinds  # :47950 foreign holder
    assert "process" in kinds  # :47952 ours but unsupervised
    assert "shim" in kinds  # dangling shim
    # The healthy, unit-managed embed server is NOT reported.
    assert not any(o.port == ra.EMBED_PORT for o in orphans)


def test_detect_orphans_silent_when_clean(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, force_linux: None
) -> None:
    monkeypatch.setattr(ra.server_proc, "find_listening_pid", lambda port, **k: None)
    monkeypatch.setattr(ra, "shim_path", lambda: tmp_path / "bin" / "absent")
    assert ra.detect_orphans() == []


def test_reap_unknown_scope_raises() -> None:
    with pytest.raises(ValueError):
        ra.reap("bogus")


# --- container-mode awareness (:47950 forwarder is ours, not foreign) -------


def test_detect_orphans_skips_our_container_port(
    monkeypatch: pytest.MonkeyPatch, force_linux: None
) -> None:
    """A running agentalloy container's :47950 forwarder is not a conflict."""
    monkeypatch.setattr(ra, "_agentalloy_container_running", lambda: True)
    # The host holder of :47950 is the runtime's port-forwarder (foreign cmdline);
    # embed/rerank run *inside* the container, so no host listener there.
    monkeypatch.setattr(
        ra.server_proc,
        "find_listening_pid",
        lambda port, **k: ra.SERVICE_PORT if port == ra.SERVICE_PORT else None,
    )
    monkeypatch.setattr(ra.server_proc, "_read_cmdline", lambda pid: "rootlessport")
    monkeypatch.setattr(ra, "shim_path", lambda: Path("/nonexistent/llama-server"))

    orphans = ra.detect_orphans()

    assert not any(o.port == ra.SERVICE_PORT for o in orphans)
    assert not any(o.kind == "conflict" for o in orphans)


def test_reap_processes_spares_our_container_port(
    monkeypatch: pytest.MonkeyPatch, force_linux: None
) -> None:
    """Reaping never warns/stops the container's :47950 forwarder."""
    monkeypatch.setattr(ra, "_agentalloy_container_running", lambda: True)
    monkeypatch.setattr(
        ra.server_proc,
        "find_listening_pid",
        lambda port, **k: ra.SERVICE_PORT if port == ra.SERVICE_PORT else None,
    )
    monkeypatch.setattr(ra.server_proc, "_read_cmdline", lambda pid: "rootlessport")
    reclaimed: list[int] = []
    monkeypatch.setattr(ra.server_proc, "reclaim_stale_port", lambda p, m: reclaimed.append(p))

    actions = ra.reap("processes", dry_run=True)

    assert not any(a.target == f"pid://{ra.SERVICE_PORT}" for a in actions)
    assert not any(a.op == "warn_foreign" for a in actions)
    assert reclaimed == []


def test_detect_orphans_reports_foreign_47950_in_native_mode(
    monkeypatch: pytest.MonkeyPatch, force_linux: None
) -> None:
    """Regression: with no container, a foreign :47950 holder is still a conflict."""
    monkeypatch.setattr(ra, "_agentalloy_container_running", lambda: False)
    monkeypatch.setattr(
        ra.server_proc,
        "find_listening_pid",
        lambda port, **k: ra.SERVICE_PORT if port == ra.SERVICE_PORT else None,
    )
    monkeypatch.setattr(ra.server_proc, "_read_cmdline", lambda pid: "nginx")
    monkeypatch.setattr(ra, "shim_path", lambda: Path("/nonexistent/llama-server"))

    orphans = ra.detect_orphans()

    assert any(o.port == ra.SERVICE_PORT and o.kind == "conflict" for o in orphans)
