"""Minimal type stubs for tantivy-py (Rust FTS library).

Tantivy is a pure-Rust full-text search library. These stubs cover the
subset of the API used by agentalloy's TantivyBM25Index (storage) and the
code-index FTS side index (code_index/fts.py). They extend the installed
tantivy-py stubs, which omit runtime members like ``SearchResult.count``
and the ``TextAnalyzerBuilder`` chain.
"""

from collections.abc import Sequence
from typing import Any

class Document:
    def __init__(self) -> None: ...
    def add_text(self, field: str, value: str) -> None: ...
    def add_float(self, field: str, value: float) -> None: ...
    def add_integer(self, field: str, value: int) -> None: ...
    def get_first(self, field: str) -> str: ...
    def __getitem__(self, field: str) -> list[Any]: ...

class SchemaBuilder:
    def add_text_field(
        self,
        name: str,
        *,
        stored: bool = False,
        tokenizer_name: str = "default",
        index_option: str = "position",
    ) -> Any: ...
    def build(self) -> Schema: ...

class Schema: ...

class Query:
    @staticmethod
    def term_query(
        schema: Schema, field: str, value: str, index_option: str = "position"
    ) -> Query: ...
    @staticmethod
    def boolean_query(subqueries: Sequence[tuple[Any, Query]]) -> Query: ...
    @staticmethod
    def all_query() -> Query: ...

class Occur:
    Must: Any
    Should: Any
    MustNot: Any

class Tokenizer:
    @staticmethod
    def regex(pattern: str) -> Tokenizer: ...

class Filter:
    @staticmethod
    def lowercase() -> Filter: ...

class TextAnalyzer: ...

class TextAnalyzerBuilder:
    def __init__(self, tokenizer: Tokenizer) -> None: ...
    def filter(self, f: Filter) -> TextAnalyzerBuilder: ...
    def build(self) -> TextAnalyzer: ...

class IndexWriter:
    def add_document(self, doc: Document) -> None: ...
    def delete_documents(self, field: str, value: str) -> None: ...
    def delete_all_documents(self) -> None: ...
    def commit(self) -> None: ...

class SearchResult:
    count: int
    hits: list[tuple[float, Any]]

class Searcher:
    num_docs: int
    def search(self, query: Query, limit: int) -> SearchResult: ...
    def doc(self, doc_addr: Any) -> Document: ...

class Index:
    schema: Schema
    def __init__(self, schema: Schema, path: str | None = None) -> None: ...
    @staticmethod
    def open(path: str) -> Index: ...
    def register_tokenizer(self, name: str, analyzer: TextAnalyzer) -> None: ...
    def writer(self) -> IndexWriter: ...
    def searcher(self) -> Searcher: ...
    def reload(self) -> None: ...
    def parse_query(
        self, query: str, default_field_names: Sequence[str] | None = None
    ) -> Query: ...
    def parse_query_lenient(
        self, query: str, default_field_names: Sequence[str] | None = None
    ) -> tuple[Query, list[Any]]: ...

def parse_query(query: str) -> Any: ...
