"""Minimal type stubs for tantivy-py (Rust FTS library).

Tantivy is a pure-Rust full-text search library. These stubs cover the
subset of the API used by agentalloy's TantivyBM25Index.
"""

from collections.abc import Sequence
from typing import Any

class Document:
    def __init__(self) -> None: ...
    def add_text(self, field: str, value: str) -> None: ...
    def add_float(self, field: str, value: float) -> None: ...
    def add_integer(self, field: str, value: int) -> None: ...
    def __getitem__(self, field: str) -> list[Any]: ...

class SchemaBuilder:
    def add_text_field(self, name: str, *, stored: bool = False) -> Any: ...
    def build(self) -> Schema: ...

class Schema: ...

class Query:
    @staticmethod
    def term_query(
        schema: Schema, field: str, value: str, index_option: str = "position"
    ) -> Query: ...
    @staticmethod
    def boolean_query(subqueries: Sequence[tuple[Any, Query]]) -> Query: ...
    @staticmethod
    def all_query() -> Query: ...

class Occur:
    Must: Any
    Should: Any
    MustNot: Any

class IndexWriter:
    def add_document(self, doc: Document) -> None: ...
    def delete_documents(self, field: str, value: str) -> None: ...
    def delete_all_documents(self) -> None: ...
    def commit(self) -> None: ...

class SearchResult:
    count: int
    hits: list[tuple[float, Any]]

class Searcher:
    def search(self, query: Query, limit: int) -> SearchResult: ...
    def doc(self, doc_addr: Any) -> Document: ...

class Index:
    schema: Schema
    def __init__(self, schema: Schema, path: str | None = None) -> None: ...
    def writer(self) -> IndexWriter: ...
    def searcher(self) -> Searcher: ...
    def reload(self) -> None: ...
    def parse_query(
        self, query: str, default_field_names: Sequence[str] | None = None
    ) -> Query: ...

def parse_query(query: str) -> Any: ...
