"""State-independent host sanitizer — the engine behind ``cleanup --deep``.

The lifecycle verbs ``cleanup`` and ``uninstall`` are *state-driven*: they remove
what ``install-state.json`` records. Across repeated install/uninstall churn the
state file drifts or is lost, and artifacts survive — orphaned llama-servers,
container/volume corpses from interrupted installs, downloaded models, the corpus,
and per-repo proxy carriers (``.claude/settings.local.json``) in repos the state
never tracked.

This module discovers AgentAlloy artifacts by their **known absolute locations**,
independent of state, and removes them for a true blank slate. It is the
deterministic equivalent of telling an agent "sanitize this host of agentalloy
runtimes".

Foreign-safety (the load-bearing invariant)
-------------------------------------------
A llama-server, binary, or GGUF that predates AgentAlloy is **never** touched:

- process kills go through :func:`runtime_artifacts.reap` /
  :func:`server_proc.stop`; the deep catch-all only kills a ``llama-server``
  whose cmdline references a path under our data dir (an unambiguously-ours
  discriminator no foreign server could carry);
- the ``~/.local/bin/llama-server`` shim is removed only when it carries the
  ``"Auto-generated by"`` sentinel (handled inside ``reap``);
- the filesystem purge only ever ``rmtree``s agentalloy-namespaced directories;
- a foreign process holding one of our ports is surfaced as a warning, never
  killed.
"""

from __future__ import annotations

import dataclasses
import json
import os
import subprocess
from pathlib import Path
from typing import Any, cast

from agentalloy.install import runtime_artifacts, server_proc, state
from agentalloy.install.runtime_artifacts import Action
from agentalloy.install.subcommands import container_runtime

# Container artifacts, by their fixed names (mirrors server_proc.DEFAULT_CONTAINER_NAME
# and uninstall._COMPOSE_NAMED_VOLUMES — the single sources of truth for these).
_CONTAINER_NAME = server_proc.DEFAULT_CONTAINER_NAME  # "agentalloy"
_VOLUME_NAMES: tuple[str, ...] = ("agentalloy-data",)
_IMAGE = container_runtime.DEFAULT_IMAGE

# $HOME-scan pruning. Heavy/irrelevant trees are skipped so the carrier walk
# stays bounded. The home-level set additionally skips the user's own global
# config dirs (we want per-repo ``<repo>/.claude`` carriers, not ``~/.claude``).
_PRUNE_DIRS: frozenset[str] = frozenset(
    {
        ".git",
        "node_modules",
        "__pycache__",
        ".venv",
        "venv",
        ".tox",
        "site-packages",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        "dist",
        "build",
        ".next",
        "target",
        ".idea",
    }
)
_HOME_TOP_SKIP: frozenset[str] = _PRUNE_DIRS | frozenset(
    {
        ".claude",
        ".cache",
        ".local",
        ".config",
        ".mozilla",
        ".npm",
        ".cargo",
        ".rustup",
        ".gradle",
        ".m2",
        ".docker",
        ".vscode-server",
        "Library",
        "go",
        "snap",
        ".pyenv",
        ".rbenv",
    }
)
_MAX_SCAN_DEPTH = 12


@dataclasses.dataclass
class SanitizeReport:
    """Outcome of a :func:`sanitize` pass (a plan when ``dry_run``)."""

    actions: list[Action]  # ordered steps — executed, or would-be under dry_run
    warnings: list[str]  # advisory notes (foreign holders, removal failures)
    cli_hint: str | None  # how to remove the CLI itself, if detectable


# ---------------------------------------------------------------------------
# Deep process catch-all (foreign-safe via data-dir discriminator)
# ---------------------------------------------------------------------------


def _orphan_llama_servers(data_dir: Path) -> list[int]:
    """PIDs of ``llama-server`` processes whose cmdline references our data dir.

    The data-dir path (e.g. ``~/.local/share/agentalloy``) is the discriminator:
    a llama-server that predates AgentAlloy serves models from elsewhere and will
    never match, so this catches *our* orphans (launched outside systemd / on a
    non-standard port, which the port-signature reaping in ``reap`` misses)
    without ever risking a foreign server. Best-effort; never raises.
    """
    needle = str(data_dir)
    try:
        result = subprocess.run(
            ["ps", "-eo", "pid=,args="],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return []
    self_pid = os.getpid()
    found: list[int] = []
    for line in result.stdout.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        parts = stripped.split(maxsplit=1)
        if len(parts) != 2:
            continue
        pid_str, args = parts
        if "llama-server" not in args or needle not in args:
            continue
        try:
            pid = int(pid_str)
        except ValueError:
            continue
        if pid == self_pid:
            continue
        found.append(pid)
    return found


# ---------------------------------------------------------------------------
# Container teardown (state-independent, by fixed names)
# ---------------------------------------------------------------------------


def _run_cmd(cmd: list[str], *, timeout: int) -> subprocess.CompletedProcess[str] | None:
    try:
        return subprocess.run(cmd, capture_output=True, text=True, timeout=timeout, check=False)
    except (OSError, subprocess.SubprocessError):
        return None


def _exists(binary: str, inspect_args: list[str]) -> bool:
    """True if ``<binary> <inspect_args...>`` reports the artifact present."""
    result = _run_cmd([binary, *inspect_args], timeout=15)
    return result is not None and result.returncode == 0


def _teardown_containers(*, dry_run: bool) -> tuple[list[Action], list[str]]:
    """Remove the agentalloy container, named volume, and image from every runtime.

    Probes both podman and docker (whichever are installed) by fixed name, so an
    orphaned container the install state never recorded is still found. Order
    matters: the container is removed before the volume/image it pins. Idempotent
    — absent artifacts are simply skipped.
    """
    import shutil

    actions: list[Action] = []
    warnings: list[str] = []
    runtimes = [c for c in ("podman", "docker") if shutil.which(c) is not None]
    if not runtimes:
        return actions, warnings

    for binary in runtimes:
        # (op, inspect-probe, remove-cmd, human target) — container first.
        targets: list[tuple[str, list[str], list[str], str]] = [
            (
                "container_rm",
                ["container", "inspect", _CONTAINER_NAME],
                ["rm", "-f", _CONTAINER_NAME],
                _CONTAINER_NAME,
            )
        ]
        for vol in _VOLUME_NAMES:
            targets.append(
                ("volume_rm", ["volume", "inspect", vol], ["volume", "rm", "-f", vol], vol)
            )
        targets.append(("image_rm", ["image", "inspect", _IMAGE], ["rmi", "-f", _IMAGE], _IMAGE))

        for op, probe, rm_args, target in targets:
            if not _exists(binary, probe):
                continue
            label = f"{binary}:{target}"
            if dry_run:
                actions.append(Action(op, label, f"would {binary} remove {target}", executed=False))
                continue
            result = _run_cmd([binary, *rm_args], timeout=60)
            if result is None:
                warnings.append(f"{binary} remove {target}: runtime not available")
                continue
            if result.returncode == 0:
                actions.append(Action(op, label, f"{binary} removed {target}", executed=True))
            else:
                stderr = (result.stderr or "").strip()
                low = stderr.lower()
                if "no such" in low or "not found" in low:
                    continue  # raced to gone — idempotent
                warnings.append(f"{binary} remove {target} failed: {stderr or 'unknown error'}")
    return actions, warnings


# ---------------------------------------------------------------------------
# Per-repo wiring sweep (state repos + $HOME carrier scan)
# ---------------------------------------------------------------------------


def _is_claude_carrier(settings_path: Path) -> bool:
    """True iff a ``.claude/settings.local.json`` carries *our* proxy base URL.

    Mirrors the discriminator in ``uninstall_proxy._unwire_proxy_claude_code_settings``
    (``env.ANTHROPIC_BASE_URL`` containing ``/proj/``), so a user's own base URL is
    never mistaken for our carrier.
    """
    try:
        raw = json.loads(settings_path.read_text())
    except (OSError, json.JSONDecodeError, ValueError):
        return False
    if not isinstance(raw, dict):
        return False
    env = cast("dict[str, Any]", raw).get("env")
    if not isinstance(env, dict):
        return False
    url = cast("dict[str, Any]", env).get("ANTHROPIC_BASE_URL")
    return isinstance(url, str) and "/proj/" in url


def _scan_home_carriers() -> list[Path]:
    """Repo roots under $HOME that hold a Claude Code proxy carrier.

    Bounded walk: heavy build/cache trees and the user's own home-level config
    dirs are pruned. Returns the repo root (the dir *containing* ``.claude``) for
    each ``.claude/settings.local.json`` that passes :func:`_is_claude_carrier`.
    """
    home = Path.home()
    repos: list[Path] = []
    for dirpath, dirnames, _filenames in os.walk(home):
        cur = Path(dirpath)
        if cur == home:
            dirnames[:] = [d for d in dirnames if d not in _HOME_TOP_SKIP]
        else:
            dirnames[:] = [d for d in dirnames if d not in _PRUNE_DIRS]
        try:
            depth = len(cur.relative_to(home).parts)
        except ValueError:
            depth = 0
        if depth >= _MAX_SCAN_DEPTH:
            dirnames[:] = []
            continue
        claude = cur / ".claude" / "settings.local.json"
        if claude.is_file() and _is_claude_carrier(claude):
            repos.append(cur)
    return repos


def _unwire_one(repo: Path, *, dry_run: bool) -> list[Action]:
    """Tear down one repo's proxy carriers + lifecycle state (idempotent)."""
    if not repo.exists():
        return []
    if dry_run:
        return [Action("unwire_repo", str(repo), f"would unwire repo {repo}", executed=False)]
    # Lazy import: the heavy uninstall module is only pulled when we actually sweep.
    from agentalloy.install.subcommands import uninstall

    proxy_removed, files_removed = uninstall._unwire_repo_local(  # pyright: ignore[reportPrivateUsage]
        repo, set(), remove_lifecycle=True
    )
    count = len(proxy_removed) + len(files_removed)
    if count == 0:
        return []
    return [Action("unwire_repo", str(repo), f"unwired {count} file(s) in {repo}", executed=True)]


def _sweep_wiring(*, dry_run: bool, scan_home: bool) -> list[Action]:
    """Sweep proxy wiring from state-recorded repos, then $HOME-discovered ones.

    Reads ``install-state.json`` for recorded ``repo_root`` entries, then (when
    ``scan_home``) walks $HOME for carriers in repos the state never tracked —
    the documented leftover gap. Each repo is swept at most once.
    """
    actions: list[Action] = []
    swept: set[Path] = set()

    def _sweep(repo: Path) -> None:
        try:
            resolved = repo.resolve()
        except OSError:
            return
        if resolved in swept:
            return
        swept.add(resolved)
        actions.extend(_unwire_one(repo, dry_run=dry_run))

    st = state.load_state()
    entries_raw = st.get("harness_files_written")
    entries: list[Any] = cast("list[Any]", entries_raw) if isinstance(entries_raw, list) else []
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        rr = cast("dict[str, Any]", entry).get("repo_root")
        if isinstance(rr, str) and rr:
            _sweep(Path(rr))

    if scan_home:
        for repo in _scan_home_carriers():
            _sweep(repo)

    return actions


# ---------------------------------------------------------------------------
# Filesystem purge
# ---------------------------------------------------------------------------


def _remove_dir(path: Path, *, dry_run: bool, warnings: list[str]) -> Action | None:
    import shutil

    if not path.exists():
        return None
    if dry_run:
        return Action("remove_dir", str(path), f"would remove {path}", executed=False)
    try:
        shutil.rmtree(path)
        return Action("remove_dir", str(path), f"removed {path}", executed=True)
    except OSError as exc:
        warnings.append(f"failed to remove {path}: {exc}")
        return Action("remove_dir", str(path), f"could not remove {path}: {exc}", executed=False)


# ---------------------------------------------------------------------------
# CLI-removal hint (the CLI itself is intentionally NOT removed)
# ---------------------------------------------------------------------------


def _cli_hint() -> str | None:
    from agentalloy.install.subcommands import uninstall

    try:
        info = uninstall._detect_install_mode()  # pyright: ignore[reportPrivateUsage]
    except Exception:  # noqa: BLE001 — a best-effort hint must never break sanitize
        return None
    mode = info.get("mode")
    if mode == "uv_tool":
        return "uv tool uninstall agentalloy"
    if mode == "pipx":
        return "pipx uninstall agentalloy"
    if mode == "editable":
        return "editable install — remove your source checkout / venv to uninstall the CLI"
    return None


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def sanitize(*, dry_run: bool, scan_home: bool) -> SanitizeReport:
    """Discover and remove every AgentAlloy host artifact, independent of state.

    Order: stop processes → free container mounts → sweep wiring (reads state) →
    delete directories (config dir LAST, since the sweep reads it). With
    ``dry_run`` nothing is mutated and the returned actions describe the plan.
    """
    actions: list[Action] = []
    warnings: list[str] = []

    # 1. Runtimes: processes, service units, shim — all foreign-safe inside reap.
    for act in runtime_artifacts.reap("all", dry_run=dry_run):
        if act.op == "warn_foreign":
            warnings.append(act.summary)  # foreign holder — reported, never killed
        else:
            actions.append(act)

    # 2. Deep catch-all: our own orphaned llama-servers (data-dir discriminator).
    data_dir = state.user_data_dir()
    for pid in _orphan_llama_servers(data_dir):
        if dry_run:
            actions.append(
                Action(
                    "kill_orphan", f"pid://{pid}", f"would stop orphan llama-server {pid}", False
                )
            )
            continue
        try:
            server_proc.stop(pid)
            actions.append(
                Action("kill_orphan", f"pid://{pid}", f"stopped orphan llama-server {pid}", True)
            )
        except server_proc.ServerLifecycleError as exc:
            warnings.append(f"could not stop orphan llama-server {pid}: {exc}")

    # 3. Containers (state-independent, both runtimes).
    c_actions, c_warnings = _teardown_containers(dry_run=dry_run)
    actions.extend(c_actions)
    warnings.extend(c_warnings)

    # 4. Per-repo wiring (reads state BEFORE the config dir is deleted in step 5).
    actions.extend(_sweep_wiring(dry_run=dry_run, scan_home=scan_home))

    # 5. Filesystem purge — user config dir LAST (it holds the state read above).
    purge_dirs = [
        data_dir,
        Path.home() / ".cache" / "agentalloy",
        Path.home() / ".agentalloy",
        state.user_config_dir(),
    ]
    for d in purge_dirs:
        act_or_none = _remove_dir(d, dry_run=dry_run, warnings=warnings)
        if act_or_none is not None:
            actions.append(act_or_none)

    return SanitizeReport(actions=actions, warnings=warnings, cli_hint=_cli_hint())
