"""Single source of truth for AgentAlloy's on-host runtime artifacts.

A running native install leaves three classes of artifact on the host:

1. **Processes** — the FastAPI service (``uvicorn``, :47950) and the two
   llama-server runners (embed :47951, reranker :47952).
2. **Service units** — systemd user units (Linux) or launchd LaunchAgents
   (macOS) that supervise those processes.
3. **The llama-server shim** — a generated launcher on PATH
   (``~/.local/bin/llama-server``) that puts the prebuilt's shared libraries on
   the loader path.

Historically each lifecycle command (``uninstall`` / ``upgrade`` / setup)
re-derived a *partial* view of this set, so each leaked a different subset:
orphaned llama-servers running off deleted files, stranded ``-embed`` /
``-rerank`` units, and a dangling shim. This module centralises the inventory
and the reaping so every command shares one complete, foreign-safe view.

Process reaping composes :mod:`agentalloy.install.server_proc`:
``reclaim_stale_port`` only kills a listener whose ``/proc`` cmdline matches
*all* of our signature substrings, so a foreign process bound to one of our
ports is never touched. Shim removal is gated on a header sentinel so a user's
own ``llama-server`` on PATH is likewise never removed.
"""

from __future__ import annotations

import dataclasses
import logging
import os
import shutil
import subprocess
import sys
from pathlib import Path

from agentalloy.install import server_proc

logger = logging.getLogger(__name__)

# --- Ports + foreign-safe cmdline signatures -------------------------------

SERVICE_PORT = 47950
EMBED_PORT = 47951
RERANK_PORT = 47952

# (port, cmdline-match-substrings): a listener on the port is reaped only when
# its /proc/<pid>/cmdline contains *every* substring. This is the foreign-safe
# signature server_proc.reclaim_stale_port keys off — the single source of
# truth, imported by enable_service instead of re-listing the matchers there.
RUNTIME_PORTS: tuple[tuple[int, tuple[str, ...]], ...] = (
    (SERVICE_PORT, ("uvicorn", "agentalloy.app")),
    (EMBED_PORT, ("llama-server", "nomic-embed")),
    (RERANK_PORT, ("llama-server", "Qwen3-Reranker")),
)

# port -> (systemd unit name, launchd label) that supervises it.
_PORT_UNIT: dict[int, tuple[str, str]] = {
    SERVICE_PORT: ("agentalloy.service", "ai.agentalloy"),
    EMBED_PORT: ("agentalloy-embed.service", "ai.agentalloy.embed"),
    RERANK_PORT: ("agentalloy-rerank.service", "ai.agentalloy.rerank"),
}

SYSTEMD_UNITS: tuple[str, ...] = tuple(unit for unit, _ in _PORT_UNIT.values())
LAUNCHD_LABELS: tuple[str, ...] = tuple(label for _, label in _PORT_UNIT.values())

# Header marker written by pull_models._write_llama_server_wrapper. The shim is
# only ever deleted when this is present, so a user's own llama-server is safe.
SHIM_SENTINEL = "Auto-generated by"


# --- Result records --------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class Orphan:
    """A stray runtime artifact found by :func:`detect_orphans` (read-only)."""

    kind: str  # "process" | "conflict" | "shim"
    summary: str  # human-readable one-liner
    port: int | None = None
    pid: int | None = None
    path: Path | None = None


@dataclasses.dataclass(frozen=True)
class Action:
    """A reaping step performed — or, under ``dry_run``, that would be."""

    op: str  # "stop_process" | "remove_unit" | "remove_shim" | "warn_foreign" | "daemon_reload"
    target: str  # pid://<n>, a path, or a unit/label name
    summary: str
    executed: bool  # False for dry-run and for warn_foreign (advisory only)


# --- Path helpers ----------------------------------------------------------


def _systemd_user_dir() -> Path:
    config_home = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    return config_home / "systemd" / "user"


def _launchd_dir() -> Path:
    return Path.home() / "Library" / "LaunchAgents"


def shim_path() -> Path:
    """The POSIX llama-server launcher ``pull-models`` installs on PATH."""
    return Path.home() / ".local" / "bin" / "llama-server"


def _is_macos() -> bool:
    return sys.platform == "darwin"


# --- Shim inspection -------------------------------------------------------


def _read_shim(path: Path) -> str:
    try:
        return path.read_text(errors="replace")
    except OSError:
        return ""


def _shim_exec_target(text: str) -> Path | None:
    """Parse ``LLAMA_LIB_DIR="..."`` from the shim → the real binary it execs."""
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("LLAMA_LIB_DIR="):
            value = stripped.split("=", 1)[1].strip().strip("\"'")
            if value:
                return Path(value) / "llama-server"
    return None


def _shim_is_dangling(text: str) -> bool:
    """True iff *text* is our shim but the prebuilt it points at is gone."""
    if SHIM_SENTINEL not in text:
        return False
    target = _shim_exec_target(text)
    return target is not None and not target.exists()


# --- Process / supervisor probes (best-effort; never raise) ----------------


def _safe_find_pid(port: int) -> int | None:
    try:
        return server_proc.find_listening_pid(port)
    except Exception:  # noqa: BLE001 — detection must never raise
        return None


def _cmdline(pid: int) -> str:
    return server_proc._read_cmdline(pid)  # pyright: ignore[reportPrivateUsage]


def _port_alive(port: int) -> bool:
    try:
        return server_proc.port_reachable(port)
    except Exception:  # noqa: BLE001
        return False


def _unit_active(port: int) -> bool:
    """Best-effort: is the supervisor for *port* currently active?

    Used only to tell an orphaned process (no live supervisor) apart from a
    healthy one. Failures resolve to False (treat as unmanaged) — detection,
    never destruction, keys off this.
    """
    systemd_unit, launchd_label = _PORT_UNIT[port]
    try:
        if _is_macos():
            result = subprocess.run(
                ["launchctl", "list", launchd_label],
                capture_output=True,
                text=True,
                timeout=5,
                check=False,
            )
            return result.returncode == 0
        result = subprocess.run(
            ["systemctl", "--user", "is-active", systemd_unit],
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
        return result.stdout.strip() == "active"
    except (OSError, subprocess.SubprocessError):
        return False


def _agentalloy_container_running() -> bool:
    """True if a container named ``agentalloy`` is running under podman or docker.

    In container mode the host listener on :47950 is the runtime's port-forwarder
    (e.g. podman ``rootlessport``), whose cmdline does not match our native
    uvicorn signature. Recognizing our own container keeps detect/reap from
    flagging it as a foreign conflict. Any failure (no runtime, error, timeout)
    returns False — we fall back to the native cmdline classification.
    """
    for bin_name in ("podman", "docker"):
        binary = shutil.which(bin_name)
        if binary is None:
            continue
        try:
            result = subprocess.run(
                [
                    binary,
                    "ps",
                    "--filter",
                    "name=^agentalloy$",
                    "--filter",
                    "status=running",
                    "--format",
                    "{{.Names}}",
                ],
                capture_output=True,
                text=True,
                timeout=5,
                check=False,
            )
        except (OSError, subprocess.SubprocessError):
            continue
        if result.returncode == 0 and "agentalloy" in result.stdout.split():
            return True
    return False


def _safe_reclaim(port: int, match: tuple[str, ...]) -> int | None:
    try:
        return server_proc.reclaim_stale_port(port, list(match))
    except Exception:  # noqa: BLE001 — best-effort; never block the caller
        return None


# --- Low-level mutators (best-effort) --------------------------------------


def _systemctl(*args: str) -> None:
    try:
        subprocess.run(
            ["systemctl", "--user", *args], capture_output=True, text=True, timeout=15, check=False
        )
    except (OSError, subprocess.SubprocessError) as exc:
        logger.debug("systemctl %s failed: %s", args, exc)


def _launchctl(*args: str) -> None:
    try:
        subprocess.run(
            ["launchctl", *args], capture_output=True, text=True, timeout=15, check=False
        )
    except (OSError, subprocess.SubprocessError) as exc:
        logger.debug("launchctl %s failed: %s", args, exc)


def _unlink(path: Path) -> None:
    try:
        path.unlink()
    except OSError as exc:
        logger.debug("could not remove %s: %s", path, exc)


# --- Detection (read-only) -------------------------------------------------


def detect_orphans() -> list[Orphan]:
    """Scan for stray runtime artifacts. Never mutates anything.

    Surfaces three things: our own processes squatting a runtime port with no
    live supervisor (``process``), a foreign holder of one of our ports
    (``conflict`` — reported, never reaped), and a dangling llama-server shim
    (``shim``). A healthy, unit-managed stack reports nothing.
    """
    found: list[Orphan] = []
    container_active = _agentalloy_container_running()

    for port, match in RUNTIME_PORTS:
        pid = _safe_find_pid(port)
        if pid is None:
            continue
        if port == SERVICE_PORT and container_active:
            # Our own container's port-forwarder holds :47950, not an orphan.
            continue
        cmdline = _cmdline(pid)
        if cmdline and all(s in cmdline for s in match):
            if not _unit_active(port):
                found.append(
                    Orphan(
                        "process",
                        f"stale {match[0]} on :{port} (pid {pid})",
                        port=port,
                        pid=pid,
                    )
                )
        else:
            found.append(
                Orphan("conflict", f":{port} held by foreign pid {pid}", port=port, pid=pid)
            )

    shim = shim_path()
    if shim.exists() and _shim_is_dangling(_read_shim(shim)):
        found.append(Orphan("shim", f"dangling shim {shim}", path=shim))

    return found


# --- Reaping ---------------------------------------------------------------


def reap(scope: str = "all", *, dry_run: bool = False, stale_only: bool = False) -> list[Action]:
    """Reap runtime artifacts. Foreign processes and non-ours shims are spared.

    ``scope``:
      - ``"processes"`` — reclaim our stale listeners on all runtime ports.
      - ``"services"``  — stop + disable + remove our service units (all present,
        or only stale ones — present but port-dead — when ``stale_only``).
      - ``"shim"``      — remove our llama-server launcher (only when dangling if
        ``stale_only``).
      - ``"all"``       — services, then processes, then shim (full teardown).

    ``dry_run`` returns the same action list without performing anything.
    """
    if scope == "all":
        actions: list[Action] = []
        actions += _reap_services(dry_run=dry_run, stale_only=stale_only)
        actions += _reap_processes(dry_run=dry_run)
        actions += _reap_shim(dry_run=dry_run, stale_only=stale_only)
        return actions
    if scope == "processes":
        return _reap_processes(dry_run=dry_run)
    if scope == "services":
        return _reap_services(dry_run=dry_run, stale_only=stale_only)
    if scope == "shim":
        return _reap_shim(dry_run=dry_run, stale_only=stale_only)
    raise ValueError(f"unknown reap scope: {scope!r}")


def _reap_processes(*, dry_run: bool) -> list[Action]:
    actions: list[Action] = []
    container_active = _agentalloy_container_running()
    for port, match in RUNTIME_PORTS:
        pid = _safe_find_pid(port)
        if pid is None:
            continue
        if port == SERVICE_PORT and container_active:
            # Our own container's port-forwarder holds :47950 — never reap or warn.
            continue
        cmdline = _cmdline(pid)
        if not cmdline or not all(s in cmdline for s in match):
            # Foreign (or unreadable) holder — advise, never kill.
            actions.append(
                Action(
                    "warn_foreign",
                    f"pid://{pid}",
                    f":{port} held by foreign pid {pid} — left running",
                    executed=False,
                )
            )
            continue
        if dry_run:
            actions.append(
                Action(
                    "stop_process",
                    f"pid://{pid}",
                    f"stop {match[0]} on :{port} (pid {pid})",
                    executed=False,
                )
            )
            continue
        reaped = _safe_reclaim(port, match)
        actions.append(
            Action(
                "stop_process",
                f"pid://{pid}",
                f"stopped {match[0]} on :{port} (pid {pid})",
                executed=reaped is not None,
            )
        )
    return actions


def _reap_services(*, dry_run: bool, stale_only: bool) -> list[Action]:
    if _is_macos():
        return _reap_launchd(dry_run=dry_run, stale_only=stale_only)
    return _reap_systemd(dry_run=dry_run, stale_only=stale_only)


def _reap_systemd(*, dry_run: bool, stale_only: bool) -> list[Action]:
    unit_dir = _systemd_user_dir()
    actions: list[Action] = []
    removed_any = False
    for port, (unit, _label) in _PORT_UNIT.items():
        unit_path = unit_dir / unit
        if not unit_path.exists():
            continue
        if stale_only and _port_alive(port):
            continue  # live, presumably-healthy — leave it for a real uninstall
        if dry_run:
            actions.append(
                Action("remove_unit", str(unit_path), f"disable + remove {unit}", executed=False)
            )
            continue
        _systemctl("disable", "--now", unit)
        _unlink(unit_path)
        actions.append(
            Action("remove_unit", str(unit_path), f"disabled + removed {unit}", executed=True)
        )
        # The sanitized env file is written next to the main service unit.
        if unit == "agentalloy.service":
            env_file = unit_dir / "agentalloy.env"
            if env_file.exists():
                _unlink(env_file)
                actions.append(
                    Action("remove_unit", str(env_file), "removed agentalloy.env", executed=True)
                )
        removed_any = True
    if removed_any and not dry_run:
        _systemctl("daemon-reload")
        actions.append(Action("daemon_reload", "systemd", "daemon-reload", executed=True))
    return actions


def _reap_launchd(*, dry_run: bool, stale_only: bool) -> list[Action]:
    agents_dir = _launchd_dir()
    actions: list[Action] = []
    for port, (_unit, label) in _PORT_UNIT.items():
        plist = agents_dir / f"{label}.plist"
        if not plist.exists():
            continue
        if stale_only and _port_alive(port):
            continue
        if dry_run:
            actions.append(
                Action("remove_unit", str(plist), f"unload + remove {label}", executed=False)
            )
            continue
        _launchctl("unload", str(plist))
        _unlink(plist)
        actions.append(
            Action("remove_unit", str(plist), f"unloaded + removed {label}", executed=True)
        )
    return actions


def _reap_shim(*, dry_run: bool, stale_only: bool) -> list[Action]:
    shim = shim_path()
    if not shim.exists():
        return []
    text = _read_shim(shim)
    if SHIM_SENTINEL not in text:
        return []  # a user's own llama-server on PATH — never ours to remove
    if stale_only:
        target = _shim_exec_target(text)
        if target is not None and target.exists():
            return []  # still points at a live prebuilt — keep it
    if dry_run:
        return [Action("remove_shim", str(shim), f"remove shim {shim}", executed=False)]
    _unlink(shim)
    return [Action("remove_shim", str(shim), f"removed shim {shim}", executed=True)]
