"""``write-env`` subcommand.

Validate + write ``.env`` from a preset template.

Preset templates live in ``src/agentalloy/install/presets/<name>.yaml``.
Presets are named by hardware target (cpu / nvidia / radeon /
apple-silicon). llama-server (llama.cpp) is the sole inference runner:
the embed server listens on 47951 and the reranker server on 47952.

The ``--port`` flag records the agentalloy service port (default 47950)
for use by ``wire-harness``.
"""

from __future__ import annotations

import argparse
import contextlib
import json
import sys
from pathlib import Path
from typing import Any

import yaml

from agentalloy.install import port_guard
from agentalloy.install import state as install_state

SCHEMA_VERSION = 1
DEFAULT_PORT = 47950

# Presets are named by hardware target only. llama-server (llama.cpp) is the
# sole inference runner; the hardware difference is handled at server start via
# ``-ngl``, not by the preset env content.
VALID_PRESETS = frozenset(
    {
        "cpu",
        "apple-silicon",
        "nvidia",
        "radeon",
    }
)

# Keys the user is allowed to override via --overrides.
_KNOWN_KEYS = frozenset(
    {
        "LADYBUG_DB_PATH",
        "DUCKDB_PATH",
        "RUNTIME_EMBED_BASE_URL",
        "RUNTIME_EMBEDDING_MODEL",
        "SIGNAL_INTENT_BACKEND",
        "SIGNAL_INTENT_RERANK_URL",
        "SIGNAL_INTENT_RERANK_MODEL",
        "DEDUP_HARD_THRESHOLD",
        "DEDUP_SOFT_THRESHOLD",
        "BOUNCE_BUDGET",
        "LOG_LEVEL",
    }
)

# Sentinel comment marking a CLI-generated .env
_SENTINEL = "# Generated by agentalloy install write-env"


def _load_preset(name: str) -> dict[str, str]:
    """Load a preset YAML from the presets package directory."""
    presets_dir = Path(__file__).resolve().parent.parent / "presets"
    preset_file = presets_dir / f"{name}.yaml"
    if not preset_file.exists():
        print(f"ERROR: Unknown preset '{name}'", file=sys.stderr)
        print(f"CAUSE: No preset template at {preset_file}", file=sys.stderr)
        print(f"FIX:   Use one of: {', '.join(sorted(VALID_PRESETS))}", file=sys.stderr)
        raise SystemExit(1)
    data = yaml.safe_load(preset_file.read_text())
    return data.get("defaults", {})


def _parse_overrides(override_args: list[str] | None) -> dict[str, str]:
    """Parse KEY=VALUE override pairs, rejecting unknown keys."""
    if not override_args:
        return {}
    overrides: dict[str, str] = {}
    for item in override_args:
        if "=" not in item:
            print(f"ERROR: Invalid override format: '{item}'", file=sys.stderr)
            print("CAUSE: Overrides must be KEY=VALUE pairs.", file=sys.stderr)
            print("FIX:   Use --overrides KEY=VALUE KEY=VALUE ...", file=sys.stderr)
            raise SystemExit(1)
        key, _, value = item.partition("=")
        if key not in _KNOWN_KEYS:
            print(f"ERROR: Unknown override key: '{key}'", file=sys.stderr)
            print("CAUSE: Typo or unsupported key.", file=sys.stderr)
            print(f"FIX:   Valid keys: {', '.join(sorted(_KNOWN_KEYS))}", file=sys.stderr)
            raise SystemExit(1)
        overrides[key] = value
    return overrides


def _validate_port_choice(port: int, values: dict[str, str]) -> None:
    """Reject a service ``--port`` that collides with a reserved or foreign port.

    Two independent gates:

    (a) Reserved-port collision — a pure VALUE comparison against the embed and
        reranker ports, enforced unconditionally. Those servers are NOT running
        at write-env time, so an occupancy probe would report them free and let
        a self-colliding port (e.g. the embed port 47951) slip through. The
        collision must be caught by comparing values, not by checking what's
        bound.

    (b) In-use collision — only when the user chose a NON-default port. Probes
        the port: a free port or one already held by agentalloy's own service is
        fine; a foreign listener is refused. The default port is exempt — it may
        legitimately be held by a prior agentalloy instance, which
        ``server_proc.reclaim_stale_port`` reclaims at serve time.
    """
    # (a) Reserved-port collision — always enforced, independent of runtime state.
    reserved = port_guard.reserved_ports(values)
    if port in reserved:
        role = reserved[port]
        print(
            f"ERROR: --port {port} is reserved for the {role} server",
            file=sys.stderr,
        )
        print(
            f"CAUSE: agentalloy runs the {role} server on port {port}; the API "
            f"service cannot share it.",
            file=sys.stderr,
        )
        print(
            f"FIX:   Choose a different --port (the embed and reranker ports, "
            f"e.g. {', '.join(str(p) for p in sorted(reserved))}, are off-limits).",
            file=sys.stderr,
        )
        raise SystemExit(1)

    # (b) In-use collision — only for a non-default port.
    if port == DEFAULT_PORT:
        return
    status, detail = port_guard.classify_port(port)
    if status in ("free", "ours"):
        return
    print(f"ERROR: --port {port} is already in use", file=sys.stderr)
    print(f"CAUSE: {detail}", file=sys.stderr)
    print(
        f"FIX:   Stop the process bound to port {port} "
        f"(try `lsof -i :{port}` to identify it), or pass a different --port.",
        file=sys.stderr,
    )
    raise SystemExit(1)


def _render_env(values: dict[str, str], preset: str, port: int) -> str:
    """Render .env file content from the merged values dict."""
    lines = [
        _SENTINEL,
        f"# Preset: {preset}, Port: {port}",
        "",
    ]
    for key in sorted(values):
        lines.append(f"{key}={values[key]}")
    lines.append("")  # trailing newline
    return "\n".join(lines)


def write_env(
    preset: str,
    port: int = DEFAULT_PORT,
    overrides: dict[str, str] | None = None,
    force: bool = False,
    root: Path | None = None,
) -> dict[str, Any]:
    """Generate and write the .env file. Returns the contract-shaped result."""
    env_path = install_state.env_path()

    # Build the merged values and validate the port choice BEFORE touching the
    # filesystem, so a rejected port leaves no backup/partial .env behind.
    defaults = _load_preset(preset)
    values: dict[str, str] = dict(defaults)
    if overrides:
        values.update(overrides)
    _validate_port_choice(port, values)

    # Read existing .env once — used for both backup and sentinel check.
    original_content: str | None = env_path.read_text() if env_path.exists() else None

    # Refuse to overwrite hand-edited .env without --force
    if original_content is not None and _SENTINEL not in original_content and not force:
        print(
            "ERROR: Cannot write .env: file exists and was not produced by a prior install",
            file=sys.stderr,
        )
        print(
            f"CAUSE: A hand-edited or third-party .env is present at {env_path}.",
            file=sys.stderr,
        )
        print(
            "FIX:   Either move the existing file aside, or run `write-env --force` to overwrite",
            file=sys.stderr,
        )
        raise SystemExit(1)

    # Backup original .env BEFORE writing — if the write fails, the original
    # must still be recoverable from the backup file (not just the in-memory
    # copy, which would be lost if the process crashes between write and
    # persisting to state).
    _backup_path: Path | None = None
    if original_content is not None:
        _backup_path = env_path.with_suffix(env_path.suffix + ".bak")
        _backup_path.write_text(original_content)
        # Backup may contain secrets; restrict to owner-only on POSIX.
        import os as _os

        with __import__("contextlib").suppress(NotImplementedError, OSError):
            _os.chmod(_backup_path, 0o600)

    content = _render_env(values, preset, port)
    install_state._atomic_write(env_path, content)  # pyright: ignore[reportPrivateUsage]

    # Persist original .env content to state for uninstall restore
    # Only store on first write (skip if already backed up)
    if original_content is not None:
        st = install_state.load_state()
        if st.get("env_original_content") is None:
            st["env_original_content"] = original_content
            install_state.save_state(st)

    # Clean up backup on success
    if _backup_path is not None:
        with contextlib.suppress(FileNotFoundError):
            _backup_path.unlink()

    # `.env` may carry tokens or runtime URLs; restrict to owner-only on
    # POSIX. Windows ignores chmod and falls back to NTFS ACL defaults.
    import os as _os

    with __import__("contextlib").suppress(NotImplementedError, OSError):
        _os.chmod(env_path, 0o600)

    return {
        "schema_version": SCHEMA_VERSION,
        "env_path": str(env_path),
        "preset": preset,
        "port": port,
        "values_written": values,
    }


# ---------------------------------------------------------------------------
# Subcommand interface
# ---------------------------------------------------------------------------


def add_parser(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:  # pyright: ignore[reportPrivateUsage]
    p: argparse.ArgumentParser = subparsers.add_parser(
        "write-env",
        help="Validate + write .env from a preset template.",
    )
    p.add_argument(
        "--preset",
        required=True,
        choices=sorted(VALID_PRESETS),
        help="Preset name to use as the base template.",
    )
    p.add_argument(
        "--port",
        type=int,
        default=DEFAULT_PORT,
        help=f"API port (default: {DEFAULT_PORT}).",
    )
    p.add_argument(
        "--overrides",
        nargs="*",
        metavar="KEY=VALUE",
        help="Override specific env values (e.g. AUTHORING_MODEL=qwen3.5:1.7b).",
    )
    p.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing hand-edited .env file.",
    )
    p.set_defaults(func=run)


def run(args: argparse.Namespace) -> int:
    """Execute the write-env subcommand.

    Always re-renders. The user may pass a different ``--port`` or
    ``--overrides`` on a re-run; caching the previous output would silently
    ignore them.
    """
    st = install_state.load_state()
    overrides = _parse_overrides(args.overrides)
    result = write_env(
        preset=args.preset,
        port=args.port,
        overrides=overrides,
        force=args.force,
    )

    fp, digest = install_state.save_output_file(result, "write-env.json")
    install_state.record_step(
        st,
        "write-env",
        extra={
            "output_digest": digest,
            "output_path": str(fp),
            "env_path": result["env_path"],
            "port": result["port"],
        },
    )
    # Also update top-level state fields
    st["env_path"] = result["env_path"]
    st["port"] = result["port"]
    install_state.save_state(st)

    if not getattr(args, "quiet", False):
        json.dump(result, sys.stdout, indent=2)
        sys.stdout.write("\n")
    return 0
